[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiosmtplib>=5.1.2",
    "aiosqlite>=0.22.1",
    "alembic>=1.18.5",
    "boto3>=1.43.62",
    "datasets>=5.0.1",
    "docling>=2.123.1",
    "fastapi[standard]>=0.139.2",
    "groq>=1.7.0",
    "pandas>=3.0.5",
    "pillow>=12.3.0",
    "psycopg2-binary>=2.9.12",
    "psycopg[binary]>=3.3.4",
    "pwdlib[argon2]>=0.3.0",
    "pydantic-settings>=2.14.2",
    "pyjwt>=2.13.0",
    "pymgclient>=1.6.0",
    "routers>=0.1.2",
    "sentence-transformers>=6.0.0",
    "sqlalchemy>=2.0.51",
]
